'use strict';

const seedBooks = [
  { isbn: '9780593311332', title: 'Tomorrow, and Tomorrow, and Tomorrow', author: 'Gabrielle Zevin', publisher: 'Knopf', category: 'Literary Fiction', price: 32.99, stock: 18, cover: 'https://covers.openlibrary.org/b/isbn/9780593311332-L.jpg', description: 'A sweeping love story about creativity, identity and the nature of collaboration across three decades of game-making.' },
  { isbn: '9780385549134', title: 'Fourth Wing', author: 'Rebecca Yarros', publisher: 'Red Tower Books', category: 'Fantasy', price: 29.99, stock: 25, cover: 'https://covers.openlibrary.org/b/isbn/9780385549134-L.jpg', description: 'Enter the brutal and elite world of a war college for dragon riders where survival is never guaranteed.' },
  { isbn: '9781250301697', title: 'Lessons in Chemistry', author: 'Bonnie Garmus', publisher: 'Doubleday', category: 'Historical Fiction', price: 27.99, stock: 12, cover: 'https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg', description: 'A chemist turned cooking show host upends 1960s America in this delightfully funny debut.' },
  { isbn: '9780593230572', title: 'Demon Copperhead', author: 'Barbara Kingsolver', publisher: 'Harper', category: 'Literary Fiction', price: 34.99, stock: 9, cover: 'https://covers.openlibrary.org/b/isbn/9780593230572-L.jpg', description: 'A Pulitzer Prize-winning retelling of David Copperfield set in the opioid crisis of Appalachia.' },
  { isbn: '9780735224292', title: 'Little Fires Everywhere', author: 'Celeste Ng', publisher: 'Penguin', category: 'Drama', price: 24.99, stock: 14, cover: 'https://covers.openlibrary.org/b/isbn/9780735224292-L.jpg', description: 'In idyllic Shaker Heights, a clash between two families ignites questions of art, identity and motherhood.' },
  { isbn: '9780802162175', title: 'The Covenant of Water', author: 'Abraham Verghese', publisher: 'Grove Atlantic', category: 'Historical Fiction', price: 36.99, stock: 7, cover: 'https://covers.openlibrary.org/b/isbn/9780802162175-L.jpg', description: 'An epic saga spanning three generations of a family in South India, celebrating life amid loss.' },
  { isbn: '9780385547970', title: 'Intermezzo', author: 'Sally Rooney', publisher: 'Farrar Straus', category: 'Literary Fiction', price: 33.99, stock: 20, cover: 'https://covers.openlibrary.org/b/isbn/9780385547970-L.jpg', description: 'Two brothers navigate grief, love and connection in Sally Rooney\'s most emotionally ambitious novel.' },
  { isbn: '9780593243145', title: 'James', author: 'Percival Everett', publisher: 'Doubleday', category: 'Historical Fiction', price: 31.99, stock: 11, cover: 'https://covers.openlibrary.org/b/isbn/9780593243145-L.jpg', description: 'A stunning reimagining of Adventures of Huckleberry Finn told from the perspective of the enslaved Jim.' },
  { isbn: '9780008628482', title: 'The Women', author: 'Kristin Hannah', publisher: 'St. Martin\'s Press', category: 'Historical Fiction', price: 30.99, stock: 16, cover: 'https://covers.openlibrary.org/b/isbn/9780008628482-L.jpg', description: 'A powerful story of female Vietnam War nurses fighting to be seen, heard and remembered.' },
  { isbn: '9781668010969', title: 'All Fours', author: 'Miranda July', publisher: 'Scribner', category: 'Literary Fiction', price: 29.99, stock: 8, cover: 'https://covers.openlibrary.org/b/isbn/9781668010969-L.jpg', description: 'A woman\'s midlife detour from Los Angeles to New York spirals into obsession and transformation.' },
  { isbn: '9780593448946', title: 'The God of the Woods', author: 'Liz Moore', publisher: 'Riverhead', category: 'Mystery & Thriller', price: 32.99, stock: 13, cover: 'https://covers.openlibrary.org/b/isbn/9780593448946-L.jpg', description: 'When a girl goes missing from an Adirondack summer camp, long-buried family secrets begin to surface.' },
  { isbn: '9781250905062', title: 'Orbital', author: 'Samantha Harvey', publisher: 'Grove Press', category: 'Literary Fiction', price: 28.99, stock: 10, cover: 'https://covers.openlibrary.org/b/isbn/9781250905062-L.jpg', description: 'Six astronauts orbit Earth, watching sixteen sunrises in a single day-a Booker Prize-winning meditation on humanity.' },
];

module.exports = { seedBooks };
